version: 2

sources:
  - name: big_query_landing
    schema: landing
    tables:
      - name: employee
        identifier: "Employee"
        description: "This table contains employee records with their personal and job-related information."
        columns:
          - name: EmpID
            description: "The unique identifier for each employee."
            tests:
              - unique
              - not_null
          - name: FirstName
            description: "The first name of the employee."
          - name: LastName
            description: "The last name of the employee."
          - name: StartDate
            description: "The date when the employee started."
          - name: ExitDate
            description: "The date when the employee exited the company, if applicable."
          - name: Title
            description: "The job title of the employee."
          - name: Supervisor
            description: "The supervisor of the employee."
          - name: ADEmail
            description: "The Active Directory email of the employee."
          - name: BusinessUnit
            description: "The business unit the employee belongs to."
          - name: EmployeeStatus
            description: "The status of the employee (e.g., active, terminated)."
          - name: EmployeeType
            description: "The type of employee (e.g., full-time, part-time)."
          - name: PayZone
            description: "The pay zone for the employee."
          - name: EmployeeClassificationType
            description: "The classification type of the employee."
          - name: TerminationType
            description: "The type of termination if applicable."
          - name: TerminationDescription
            description: "Description of the termination circumstances."
          - name: DepartmentType
            description: "Type of the department the employee works in."
          - name: Division
            description: "The division the employee works in."
          - name: DOB
            description: "The date of birth of the employee."
          - name: State
            description: "The state where the employee is located."
          - name: JobFunctionDescription
            description: "A description of the employee's job functions."
          - name: GenderCode
            description: "The gender code of the employee."
          - name: LocationCode
            description: "The location code where the employee works."
          - name: RaceDesc
            description: "Description of the employee's race."
          - name: MaritalDesc
            description: "Marital status description of the employee."
          - name: Performance Score
            description: "The performance score of the employee."
          - name: Current Employee Rating
            description: "The current rating of the employee."
